config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root 'home#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
    resources :categories, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  scope :with_color_and_products_in, -> (product_ids) do
    joins(:option_type, :variants).
      where("spree_option_types.name = ?", "tshirt-color").
      where("spree_variants.product_id IN (?)", product_ids).
      distinct
  end

  scope :with_size_and_products_in, ->(product_ids) do
    joins(:option_type, :variants).
      where("spree_option_types.name = ?", "tshirt-size").
      where("spree_variants.product_id IN (?)", product_ids).
      distinct
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  MAX_PRODUCTS_TO_FETCH = 20

  scope :new_arrivals, -> { order(available_on: :desc) }
  scope :without_product, ->(product) { where.not(id: product.id) }
  scope :includes_image_and_price, -> { includes(master: [:images, :default_price]) }
  scope :includes_variants, -> { includes(:variants) }

  scope :filter_by_option, -> (option) {
    if option[:option_value].present?
      joins(variants: :option_values).
        where(spree_option_values: { name: option[:option_value] })
    end
  }

  add_search_scope :with_color do |color|
    if color.nil?
      all
    else
      includes(variants_including_master: :option_values).
        where("spree_option_values.name = ? AND spree_option_values.option_type_id = ?",
              color, Spree::OptionType.find_by(name: "tshirt-color")).references(:option_values)
    end
  end

  add_search_scope :with_size do |size|
    if size.nil?
      all
    else
      includes(variants_including_master: :option_values).
        where("spree_option_values.name = ? AND spree_option_values.option_type_id = ?",
              size, Spree::OptionType.find_by(name: "tshirt-size")).references(:option_values)
    end
  end

  def related_products
    self.class.joins(:taxons).
      includes_image_and_price.
      includes_variants.
      where(spree_taxons: { id: taxons.ids }).
      without_product(self).
      distinct.
      limit(MAX_PRODUCTS_TO_FETCH)
  end

  scope :order_descend_by_price, -> { joins(:prices).order("spree_prices.amount DESC") }
  scope :order_ascend_by_price, -> { joins(:prices).order("spree_prices.amount ASC") }
  scope :order_newest_by_product_available_on, -> { joins(:taxons).order("spree_products.available_on DESC") }
  scope :order_oldest_by_product_available_on, -> { joins(:taxons).order("spree_products.available_on ASC") }
  scope :order_by, ->(order) {
    case order
    when 'price-dsc' then order_descend_by_price
    when 'price-asc' then order_ascend_by_price
    when 'oldest'    then order_oldest_by_product_available_on
    else order_newest_by_product_available_on
    end
  }

  def self.order_option_hash
    {
      "新着順":      'newest',
      "価格の安い順": 'price-asc',
      "価格の高い順": 'price-dsc',
      "古い順":      'oldest',
    }
  end
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  scope :includes_variants, -> { includes(:variants) }

  def products_with_self_and_descendants
    scope = Spree::Product.includes(:taxons, master: [:images, :default_price]).includes_variants
    scope.where(
      spree_taxons: { id: self_and_descendants.pluck(:id) }
    )
  end
end

app/models/spree/taxonomy_decorator.rb
Spree::Taxonomy.class_eval do
  def root_taxons
    taxons.where(parent_id: root.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @products = @taxon.products_with_self_and_descendants.
      with_color(params[:color]).with_size(params[:size]).
      filter_by_option(option_value: params[:option_value]).
      order_by(params[:order])
    @taxonomies = Spree::Taxonomy.includes(:root)
    @list_of_colors = Spree::OptionValue.with_color_and_products_in(@products.ids)
    @list_of_sizes = Spree::OptionValue.with_size_and_products_in(@products.ids)
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NEW_PRODUCTS_IN_PAGE = 10

  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Search
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Pricing

  def index
    @new_products = Spree::Product.includes_image_and_price.new_arrivals.includes_variants.limit(MAX_NEW_PRODUCTS_IN_PAGE)
    @clothing = Spree::Taxon.where(name: "Clothing")
    @bags = Spree::Taxon.where(name: "Bags")
    @mugs = Spree::Taxon.where(name: "Mugs")
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  NUM_RELATED_PRODUCTS_TO_DISPLAY = 4

  def show
    @product = Spree::Product.find(params[:id])
    @product_properties = @product.product_properties.includes(:property)
    @variant = @product.variants.find_by(id: params[:variant_id])
    @images = (@variant || @product).images
    @related_products = @product.related_products.sample(NUM_RELATED_PRODUCTS_TO_DISPLAY)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "BIGBAG Store"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def grid_layout?
    !list_layout?
  end

  def list_layout?
    params[:layout] == "list"
  end
end

app/views/layouts/_head.html.erb
<head>
  <!-- SITE TITTLE -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.css" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  <!-- PLUGINS CSS STYLE -->

  <!-- GOOGLE FONT -->
  <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

  <!-- CUSTOM CSS -->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
            <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li><span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span></li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>$0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT <br><span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to potepan_root_path, class: "navbar-brand" do %>
         <%= image_tag("img/logo.png", :alt => "") %>
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= potepan_root_path %>">Home</a></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li><%= link_to "Categories", potepan_category_path(1) %></li>
                  <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li class="active"><%= link_to "Single Product", potepan_product_path(1) %></li>
                  <li><a href="cart_page.html">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                  <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                  <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                  <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                  <li><a href="checkout_complete.html">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li><a href="about_us.html">About Us</a></li>
              <li><a href="signup.html">Register</a></li>
              <li><a href="signup-login.html">Register or Login</a></li>
              <li><a href="login.html">Login</a></li>
              <li><a href="lost-password.html">Password Recovery</a></li>
              <li><a href="privacy_policy.html">Privacy Policy</a></li>
              <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
              <li><a href="404.html">404 Not Found</a></li>
              <li><a href="coming-soon.html">Coming Soon</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="blog_right_sidebar.html">Right Sidebar</a></li>
              <li><a href="blog_left_sidebar.html">Left Sidebar</a></li>
              <li><a href="blog-fullwidth.html">Full Width</a></li>
              <li><a href="blog-single-fullwidth.html">Single Post</a></li>
              <li><a href="blog_single_right_sidebar.html">Single Right Sidebar</a></li>
              <li><a href="blog_single_left_sidebar.html">Single Left Sidebar</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="account-dashboard.html">Dashboard</a></li>
              <li><a href="account-profile.html">Profile</a></li>
              <li><a href="account-all-orders.html">All Orders</a></li>
              <li><a href="account-single-order.html">Single Order</a></li>
              <li><a href="account-wishlist.html">Wishlist</a></li>
              <li><a href="account-address.html">Address</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_categories.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= taxonomy.name %></div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomy.root_taxons.each do |taxon| %>
          <% if taxon.leaf? %>
            <li>
              <%= link_to potepan_category_path(taxon.id) do %>
                <i class="fa"></i><%= "#{taxon.name} (#{taxon.products.count})" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <a href="<%= "javascript:;" %>" data-toggle="collapse" data-target="#taxon-<%= taxon.id %>">
                <%= "#{taxon.name} (#{taxon.products_with_self_and_descendants.count})" %>
                <i class="fa fa-plus"></i>
              </a>
              <ul id="taxon-<%= taxon.id %>" class="collapse collapseItem">
                <% taxon.descendants.each do |taxon_child| %>
                  <li>
                    <%= link_to potepan_category_path(taxon_child.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= "#{taxon_child.name} (#{taxon_child.products.count})" %>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_color_filter.html.erb
<% if colors.any? %>
  <div class="panel panel-default filterNormal filterColor">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <li>
          <% colors.each do |color| %>
            <%= link_to potepan_category_path(taxon.id, color: color.name) do %>
              <%= color.presentation %> <span>(<%= color.variants.select(:product_id).distinct.count %>)</span>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/potepan/categories/_grid_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment.url(:product)) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li>
            <a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a>
          </li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a data-toggle="modal" href=".quick-view" class="btn btn-default" data-target="#product-<%= product.id %>"><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product.id) do %>
        <h5><%= product.name %></h5>
      <% end %>
      <h3><%= product.display_price %></h3>
    </div>
  </div>
</div>

app/views/potepan/categories/_list_product.html.erb
<div class="col-xs-12">
  <div class="media">
    <div class="media-left">
      <%= image_tag(product.display_image.attachment(:product), class: "media-object", alt: "image of #{product.name}") %>
      <span class="maskingImage">
        <a data-toggle="modal" href=".quick-view" class="btn viewBtn" data-target="#product-<%= product.id %>">
          Quick View
        </a>
      </span>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to product.name, potepan_product_path(product.id) %>
      </h4>
      <p><%= product.description %></p>
      <h3><%= product.display_price %></h3>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal">
          <i class="fa fa-heart" aria-hidden="true"></i>
        </button>
        <button type="button" class="btn btn-default" onclick="location.href='../cart_page';">
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_products_sort_filter.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <%= form_tag(potepan_category_path(params[:id]), method: :get) do %>
      <%= select_tag "order", options_for_select(Spree::Product.order_option_hash, selected: params[:order] || 'newest'), { class: "select-drop", onChange: "this.form.submit()" } %>
    <% end %>
  </div>
  <div class="col-xs-6" id="grid_or_list">
    <div class="btn-group pull-right" role="group" id="Grid_active">
      <button type="button" class="btn btn-default <%= 'active' if grid_layout? %>" onclick= "window.location.href= '<%= potepan_category_path(taxon.id, layout: "grid")%>'">
        <i class="fa fa-th" aria-hidden="true"></i><span class='grid_btn'>Grid</span>
      </button>
    </div>
    <div class="btn-group pull-right" role="group" id="List_active">
      <button type="button" class="btn btn-default <%= 'active' if list_layout? %>" onclick= "window.location.href= '<%= potepan_category_path(taxon.id, layout: "list")%>'">
        <i class="fa fa-th-list" aria-hidden="true"></i><span class='list_btn'>List</span>
      </button>
    </div>
  </div>
</div>

app/views/potepan/categories/_size_filter.html.erb
<% if sizes.any? %>
  <div class="panel panel-default filterNormal filterSize">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <li>
          <% sizes.each do |size| %>
            <%= link_to potepan_category_path(taxon.id, size: size.name) do %>
              <%= size.presentation %> <span>(<%= size.variants.select(:product_id).distinct.count %>)</span>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/potepan/home/_new_product.html.erb
<div class="slide">
  <div class="productImage clearfix">
    <%= image_tag(new_product.images.first.attachment.url(:product), alt: "featured-product-img") %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
        <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
        <li><a data-toggle="modal" href=".quick-view" class="btn btn-default" data-target="#product-<%= new_product.id %>"><i class="fa fa-eye"></i></a></li>
      </ul>
    </div>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(new_product.id) do %>
      <h5>
        <%= new_product.name %>
      </h5>
      <h3>
        <%= new_product.display_price %>
      </h3>
    <% end %>
  </div>
</div>

app/views/potepan/home/_popular_categories.html.erb
<div class="row featuredCollection">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>人気カテゴリー</h4>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='categories/<%= @clothing.ids.first %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Clothings", potepan_category_path(@clothing.ids.first), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Clothings</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='categories/<%= @bags.ids.first %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Bags", potepan_category_path(@bags.ids.first), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Bags</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-4 col-xs-12">
    <div class="thumbnail" onclick="location.href='categories/<%= @mugs.ids.first %>';">
      <div class="imageWrapper">
        <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
        <div class="masking">
          <%= link_to "View Mugs", potepan_category_path(@mugs.ids.first), class: "btn viewBtn" %>
        </div>
      </div>
      <div class="caption">
        <h4>Mugs</h4>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/_related_products.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment.url) %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li>
            <a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a>
          </li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a data-toggle="modal" href=".quick-view" class="btn btn-default" data-target="#product-<%= product.id %>"><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product.id) do %>
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/shared/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'HOME', potepan_root_path %>
          </li>
          <% if params[:controller] == "potepan/categories" %>
            <li>
              <a href="#">shop</a>
            </li>
          <% end %>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>